version: '3.8'
 
services:
  mongo:
    image: mongo:6.0
    container_name: tracking-system-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: .
    container_name: stock-project-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://admin:admin@cluster0.tgpyua2.mongodb.net/
    depends_on:
      - mongo
 
volumes:
  mongo-data: